#include <Eigen/Dense>

// This file has been generated by generate6LinkModelSymengine.py.
// Edit at your own risk.

enum RobotType
{
	UR3e,
	UR5e,
	NullBot
};


class URRobot
{
public:
	URRobot();
	URRobot(RobotType type);
	~URRobot();
	int N;
	Eigen::Matrix<double, 10, 1> gravity (Eigen::Matrix<double, 10, 1> & q);

	Eigen::Matrix<double, 6, 10> jacobian (Eigen::Matrix<double, 10, 1> & q);

	Eigen::Matrix<double, 6, 10> jacobianDot (Eigen::Matrix<double, 10, 1> & q, Eigen::Matrix<double, 10, 1> & dq);

	Eigen::Matrix<double, 10, 10> inertia (Eigen::Matrix<double, 10, 1> & q);

	Eigen::Matrix<double, 10, 10> coriolis (Eigen::Matrix<double, 10, 1> & q, Eigen::Matrix<double, 10, 1> & dq);

private: 

	double a2_;
	double a3_;
	double a6_;
	double a7_;
	double d1_;
	double d4_;
	double d5_;
	double d8_;
	double d9_;
	double d10_;
	double m_[10];
	double com_[10][3];
	double link_inertia_[10][3][3];
	double g[3];
};
